### ISSUE TITLE
(Test the deployment): ("statusCode": 404,   "message": "Tenant not found for id xxxxx")

### ISSUE THREAD

**Issue by beansandroasters** [awslabs/sbt-aws#16]
### Describe the issue

In the ["Test the deployment"](https://github.com/awslabs/sbt-aws/blob/main/docs/public/README.md#test-the-deployment) section, GET request url path is made of ${TENANT_ID} generated from shell below.
`TENANT_ID="$RANDOM"`

However, that tenant id should be the one generated in Lambda code below.
`input_details['tenantId'] = str(uuid.uuid4())`

That would be great if you could modify the doc.

### Links

https://github.com/awslabs/sbt-aws/blob/main/docs/public/README.md#test-the-deployment

**Comment by tobuck-aws** [comment]
@beansandroasters  thanks for the note, and good catch! I have a [pr](https://github.com/awslabs/sbt-aws/pull/17) in that changes to docs so the test is to get all tenants, vs. a particular one. From a test perspective, I feel this accomplishes the same thing, and without needing prior knowledge of the generated Tenant ID.
