### ISSUE TITLE
ControlPlane-TenantManagement-TenantDelete: Accepts tenant ids that don't exist

### ISSUE THREAD

**Issue by somensi-aws** [awslabs/sbt-aws#8]
### Describe the bug

When running DELETE /tenants/{tenantId}, if tenantId doesn't exist, the service accepts the request, and writes a new record to the TenantDetails DynamoDB table.

> 

### Expected Behavior

When TenantID does not exist, the service should return 404.

### Current Behavior

Returns 200 and writes new entry to TenantDetails table

### Reproduction Steps

invoke DELETE /tenant/tenantId with tenantId that does not exist in the database

### CDK CLI Version

2.131.0 (build 92b912d)

### Node.js Version

v18.19.0

### OS

Debian GNU/Linux 12 (bookworm)

### Language

TypeScript

**Comment by suhussai** [comment]
Thanks for reporting this!

Fix proposed in #11
